
# target
# a.txt : b.txt c.txt	
# 	cat b.txt c.txt > a.txt


# prerequisites

# result.txt: source.txt
# 	cp source.txt result.txt

# source.txt:
# 	echo "this is the source" > source.txt

source: file1 file2 file3



